name: Ruby CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3']
    services:
        postgres:
            image: lanterndata/lantern-self-hosted:lantern-0.4.1-extras-0.4.1-minor-1
            env:
                POSTGRES_PASSWORD: postgres
            ports:
                - 5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Set up database
      run: |
        DATABASE_NAME=db_$(echo "${{ matrix.ruby-version }}" | tr '.' '_')
        PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE $DATABASE_NAME"
    - name: Run tests
      run: |
        DATABASE_NAME=db_$(echo "${{ matrix.ruby-version }}" | tr '.' '_')
        export DATABASE_URL=postgresql://postgres:postgres@localhost:5432/$DATABASE_NAME
        bundle exec rake test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}